# Generated by Django 4.0 on 2022-01-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskName', models.CharField(max_length=90)),
                ('TaskTime', models.CharField(max_length=30)),
                ('CompletionStatus', models.BooleanField(default=False)),
            ],
        ),
    ]
