# Generated by Django 4.0 on 2021-12-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=90)),
                ('RollNumber', models.CharField(max_length=90)),
                ('Grade', models.CharField(max_length=90)),
                ('PhoneNumber', models.IntegerField(max_length=10)),
                ('FatherName', models.CharField(max_length=90)),
                ('MotherName', models.CharField(max_length=90)),
                ('Address', models.CharField(max_length=150)),
            ],
        ),
    ]
